//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        [Required]
        public int Id { get; set; }
        [Required]
        public string ProductType { get; set; }
        [Required]
        public string Quantity { get; set; }
        [Required]
        [DataType(DataType.Currency)]
        public string Price { get; set; }
        [Required]
        [DataType(DataType.DateTime)]
        public Nullable<System.DateTime> Date { get; set; }
    }
}
